DELETE FROM POST WHERE ID=-1;
DELETE FROM CATEGORY WHERE NameOfCategory="";
DELETE FROM USER_COMMENT WHERE IP='';
DELETE FROM BLOG_ADMIN WHERE AdminUsername='';
DELETE FROM SUBSCRIBED_EMAIL;

DROP TABLE CATEGORY;
DROP TABLE POST;
DROP TABLE USERCOMMENT; 
DROP TABLE BLOG_ADMIN; 
DROP TABLE SUBSCRIBED_EMAIL;