DELETE FROM POST WHERE ID=-1;
DELETE FROM CATEGORY WHERE NameOfCategory="";
DELETE FROM USER_COMMENT WHERE IP='';
DELETE FROM BLOG_ADMIN WHERE AdminUsername='';

DROP TABLE CATEGORY;
DROP TABLE POST;
DROP TABLE USERCOMMENT; 
DROP TABLE BLOG_ADMIN; 