SELECT * FROM POST;
SELECT * FROM CATEGORY;
SELECT * FROM USER_COMMENT ORDER BY Country;
SELECT * FROM BLOG_ADMIN;
SELECT * FROM SUBSCRIBED_EMAIL;
SELECT Email FROM SUBSCRIBED_EMAIL ;

SELECT (SELECT COUNT(*) FROM POST) = 7;

SET time_zone = '+03:00';
SELECT (SELECT COUNT(*) FROM USER_COMMENT WHERE DATE(CommentDate) = DATE(NOW())  ) <=2;
SELECT COUNT(*) FROM USER_COMMENT WHERE IP = '195.174.194.205' AND CAST(CommentDate AS DATE) = "2021-10-07" ;

SELECT ID FROM USER_COMMENT ORDER BY ID DESC LIMIT 0;

SELECT EXISTS(SELECT NameOfCategory FROM CATEGORY WHERE NameOfCategory='Null');

SELECT Country, COUNT(*) AS CommentsCount FROM USER_COMMENT GROUP BY Country ORDER BY Country ASC;

SELECT NameOfCategory, COUNT(*) AS NumberOfPosts FROM CATEGORY LEFT OUTER JOIN POST ON POST.Category=NameOfCategory GROUP BY NameOfCategory;

SELECT USER_COMMENT.ID AS UserCommentID, POST.Title AS PostTitle, USER_COMMENT.Nick AS UserCommentNick, USER_COMMENT.Content AS UserCommentContent FROM USER_COMMENT, POST WHERE USER_COMMENT.PostID=POST.ID ORDER BY USER_COMMENT.CommentDate DESC;

SELECT POST.ID AS PostID, POST.Content AS PostContent, POST.Category AS PostCategory, POST.CoverPhotoLink AS PostCoverPhotoLink, POST.Title AS PostTitle, POST.PostDate, COUNT(USER_COMMENT.PostID) AS NumberOfComments FROM POST LEFT OUTER JOIN USER_COMMENT ON USER_COMMENT.PostID=POST.ID GROUP BY POST.ID ORDER BY POST.PostDate DESC;

SELECT MONTH(CAST(CommentDate AS DATE)) AS CommentMonth, YEAR(CAST(CommentDate AS DATE)) AS CommentYear, COUNT(*) 
FROM USER_COMMENT 
GROUP BY CommentMonth, CommentYear ORDER BY CommentMonth, CommentYear;

SELECT NameOfCategory AS id, NameOfCategory, COUNT(POST.Category) AS NumberOfPosts FROM CATEGORY LEFT OUTER JOIN POST ON POST.Category=NameOfCategory GROUP BY NameOfCategory;

SELECT * FROM POST WHERE Category != 'Projects' AND Category != 'Private' ORDER BY POST.PostDate DESC;

SELECT table_schema AS "Database", SUM(data_length + index_length) / 1024 / 1024 AS "Size (MB)" FROM information_schema.TABLES GROUP BY table_schema;